In [16]:
library(dplyr)
library(tidyr)
library(data.table)

Attaching package: ‘data.table’


The following object is masked from ‘package:GenomicRanges’:

    shift


The following object is masked from ‘package:IRanges’:

    shift


The following objects are masked from ‘package:S4Vectors’:

    first, second


The following objects are masked from ‘package:dplyr’:

    between, first, last

In [18]:
# map gene id from one type to another
mapGeneIDs <- function(query, query_type,
                        output_types) {
  library(org.Hs.eg.db)
  mapped = AnnotationDbi::select(org.Hs.eg.db,
                  keys = query,
                  columns = output_types,
                  keytype = query_type)
  return(mapped)
}

In [2]:
setwd("~/projects/lung_scMultiomics/analysis/")

In [7]:
library(openxlsx)
summary_tbl <- readxl::read_xlsx("../output/E2G_analysis/asthma_candidate_risk_genes_43CREs.xlsx")
pops_p2g <- readRDS("../data/plotting_inputs/E2G_PoPs_by_genes.RDS")
eqtl_list <- readRDS("../output/E2G_analysis/natri2023_eQTLs.RDS")
genes <- unique(unlist(lapply(summary_tbl$LinkedGene, function(i) {strsplit(i, ",")[[1]]})))
gene_tbl <- 
  summary_tbl %>% 
    separate_rows(LinkedGene, sep = ",") %>%
    dplyr::select(-c(Peak, GeneScore, NewCREs, CandidateGenes, susie_pips)) %>%
    distinct()
prior_tbl <- 
    summary_tbl %>%
    separate_rows(CandidateGenes,sep = ",") %>%
    filter(!is.na(CandidateGenes)) %>%
    dplyr::select(CandidateGenes, LinkedGene, snps) %>%
    distinct()

In [19]:
eqtl_list <-
  lapply(c("Bcells", "CD4", "CD8NKT"), function(i) {
    eqtl <- 
      fread(sprintf("~/cluster/projects/u19_multiomics/other_data/Natri2023/immune_%s.tsv", i))
    # LFSR <= 0.05 in at least one cell type
    eqtl <- eqtl[!is.na(eqtl$snp_rsid) & eqtl$lfsr <= 0.05, ]
    eqtlDF <- do.call(
      rbind,
      lapply(eqtl$snp_id, function(i) {
        words = strsplit(i, "_")[[1]]
        return(words)
      }))
    eqtl_gr <- GRanges(seqnames = paste0("chr", eqtlDF[, 1]),
                       IRanges(start = eqtlDF[, 2]),
                       gene = eqtl$feature_id,
                       rsid = eqtl$snp_rsid,
                       lfsr = eqtl$lfsr)
    
    mapped_genes <- mapGeneIDs(query = eqtl_gr$gene, 
                               query_type = "ENSEMBL", 
                               output_types = "SYMBOL")
    eqtl_gr$targetGene <- mapped_genes$SYMBOL[match(eqtl_gr$gene, mapped_genes$ENSEMBL)]
    eqtl_gr <- eqtl_gr[!is.na(eqtl_gr$targetGene)]
    return(eqtl_gr)
  })
names(eqtl_list) <- c("B", "CD4_T", "CD8_T")

Loading required package: AnnotationDbi

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘AnnotationDbi’


The following object is masked from ‘package:dplyr’:

    select




'select()' returned many:many mapping between keys and columns

'select()' returned many:many mapping between keys and columns

'select()' returned many:many mapping between keys and columns

In [66]:
prior_tbl$PoPS <- pops_p2g$pops[match(prior_tbl$CandidateGenes, pops_p2g$SYMBOL)]

In [67]:
prior_tbl

   CandidateGenes LinkedGene          snps                    Lung_eGene
1  IL2RA          IL15RA,IL2RA        rs12722502              FALSE
2  PRKCQ          IL15RA,IL2RA        rs12722502              FALSE
3  PRKCQ          PRKCQ               rs2255088               FALSE
4  IL2RA          PRKCQ               rs2255088               FALSE
5  CXCR5          CXCR5,DDX6          rs12365699,rs4936444    FALSE
6  OVOL1          OVOL1               rs10791824              FALSE
7  LRRC32         LRRC32              rs55646091,rs11236797   FALSE
8  RPS26          ERBB3,IKZF4,RPS26   rs705704,rs705705       FALSE
9  STAT6          LRP1                rs12368672               TRUE
10 SMAD3          IQCH                rs117683492             FALSE
11 MAP2K5         IQCH                rs117683492             FALSE
12 CCR7           CCR7,SMARCE1        rs9893132               FALSE
13 SMARCE1        CCR7,SMARCE1        rs9893132                TRUE
14 CCR7           CCR7,SMARCE1        rs11656173              FALSE
15 SMARCE1        CCR7,SMARCE1        rs11656173               TRUE
16 TBX21          OSBPL7,TBX21        rs56308324              FALSE
17 TNFRSF11A      TNFRSF11A           rs8086340               FALSE
18 SLC7A10        CEBPA               rs118013485,rs117710327 FALSE
19 CEBPA          CEBPA               rs118013485,rs117710327  TRUE
20 TNFSF4         TNFSF4              rs11811856              FALSE
21 CCL20          CCL20               rs1811711                TRUE
22 D2HGDH         D2HGDH              rs5839764               FALSE
23 CCR4           CCR4,TMPPE,TRIM71   rs35570272              FALSE
24 TLR10          TLR1                rs56357984              FALSE
25 TLR1           TLR1                rs56357984              FALSE
26 IRF1           IRF1                rs2548992,rs2057656      TRUE
27 BACH2          BACH2               rs905671,rs943689       FALSE
28 ARRDC1         ARRDC1,DPH7,CACNA1B rs117137535              TRUE
   Asthma_eGene risk_genes PoPS
1  FALSE         TRUE       2.73284479
2   TRUE         TRUE       1.72350993
3   TRUE         TRUE       1.72350993
4  FALSE         TRUE       2.73284479
5  FALSE        FALSE       0.54263983
6  FALSE        FALSE       0.46379917
7  FALSE        FALSE       1.15860517
8   TRUE        FALSE       1.23469253
9  FALSE        FALSE               NA
10  TRUE        FALSE               NA
11  TRUE        FALSE               NA
12 FALSE        FALSE       0.83505408
13  TRUE        FALSE       0.44846743
14 FALSE        FALSE       0.83505408
15  TRUE        FALSE       0.44846743
16 FALSE        FALSE       2.12177147
17  TRUE        FALSE       0.63979731
18 FALSE        FALSE               NA
19 FALSE        FALSE       0.04954006
20 FALSE         TRUE       2.91110215
21 FALSE        FALSE      -0.49394398
22  TRUE        FALSE       0.67400260
23 FALSE        FALSE       1.11456105
24  TRUE        FALSE               NA
25  TRUE        FALSE       1.36887759
26 FALSE        FALSE       2.19491436
27 FALSE         TRUE       2.16544431
28  TRUE         TRUE       0.30072038

In [21]:
eqtl_pairs <-
  lapply(prior_tbl$CandidateGenes, function(i) {
    pairs <-c()
    for(ct in names(eqtl_list)) {
      if(i %in% eqtl_list[[ct]]$targetGene) {
        rows = 
          data.frame(mcols(eqtl_list[[ct]])) %>% 
            filter(targetGene == i) %>%
              mutate(CandidateGenes = targetGene,
                     snps = rsid) %>%
              dplyr::select(rsid, targetGene)
        pairs <- rbind(pairs,
          data.frame(
            "CellType" = ct,
            rows))
      }
    }
    return(pairs)
  })
eqtl_pairs <- do.call(rbind, eqtl_pairs[!sapply(eqtl_pairs, is.null)])

In [35]:
gene_tbl$Lung_eGene <- gene_tbl$LinkedGene %in% eqtl_pairs$targetGene
prior_tbl$Lung_eGene <- prior_tbl$CandidateGenes %in% eqtl_pairs$targetGene

In [48]:
riskGenes_set1 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS5_1_asthma-risk-genes_ALOFT__TableS12.txt.gz")
riskGenes_set2 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS5_2_asthma-risk-genes_GTEx__TableS13.txt.gz")

In [49]:
# The PCGs are defined as those with an FDR < 10% from INTACT - joint usage of TWAS and colocalization
quantile(riskGenes_set2$FDR_intact)

       0%       25%       50%       75%      100%
0.0000000 0.8729932 0.9340100 0.9554698 0.9753162

In [53]:
head(riskGenes_set1 %>% filter(FDR_intact < 0.1))

  Gene            symbol genetic_variant                 chromosome
1 ENSG00000073605 GSDMB  17:38051348:A:G;rs8067378       17
2 ENSG00000112182 BACH2  6:91006227:G:A;rs1504215         6
3 ENSG00000172057 ORMDL3 17:38089317:A:AAAGG;rs140683487 17
4 ENSG00000131507 NDFIP1 5:141489921:C:T;rs12653866       5
5 ENSG00000125245 GPR18  13:99910263:C:T;rs3759444       13
6 ENSG00000134882 UBAC2  13:99852753:A:G;rs2296860       13
  chr_pos_grch38 chr_pos_grch37 PIP       pval_eqtl   peaking_d pval_twas
1 17_39895095    17_38051348    0.9993510 4.42171e-34 0         1.032e-98
2 6_90296508     6_91006227     0.0662612 1.32959e-01 3         1.922e-34
3 17_39933064    17_38089317    0.9501850 9.71619e-24 0         7.714e-31
4 5_142110356    5_141489921    0.1532790 5.76374e-06 3         1.656e-25
5 13_99258009    13_99910263    0.0349365 1.49488e-02 1         2.069e-25
6 13_99200499    13_99852753    0.1820240 1.14869e-02 2         8.176e-25
  zscore_twas FDR_twas     GLCP    PCG FDR_intact
1 -21.08763   9.102756e-95 0.88220 1   0
2 -12.23907   2.119125e-31 0.11130 1   0
3  11.54626   7.560149e-28 0.80950 1   0
4  10.43836   1.270152e-22 0.97370 1   0
5 -10.41714   1.520801e-22 0.07594 1   0
6  10.28567   5.769313e-22 0.12100 1   0

In [54]:
# asthma eGene datasets
eGenes_set1 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS4_3_eGene_ALOFT_dap__TableS10.txt.gz")
eGenes_set2 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS4_4_eGene_GTEx_dap__TableS11.txt.gz")
riskGene_set1 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS5_1_asthma-risk-genes_ALOFT__TableS12.txt.gz")
riskGenes_set2 <- fread("~/cluster/projects/u19_multiomics/other_data/weilong/TableS5_2_asthma-risk-genes_GTEx__TableS13.txt.gz")

eGenes_combined <- rbind(
  data.frame(study = "ALOFT", eGenes_set1),
  data.frame(study = "GTEx", eGenes_set2)
)
riskGenes_combined <- unique(
    c(riskGenes_set1$symbol[riskGenes_set1$FDR_intact < 0.1],
      riskGenes_set2$symbol[riskGenes_set1$FDR_intact < 0.1])
    )
mapping <- 
  mapGeneIDs(eGenes_combined$gene, 
             query_type  = "ENSEMBL", 
             output_types = "SYMBOL")
eGenes_combined$eGenes <- 
  mapping$SYMBOL[match(eGenes_combined$gene, mapping$ENSEMBL)]

eGenes_combined %>% filter(eGenes %in% genes)

'select()' returned 1:many mapping between keys and columns

   study gene            lfdr       FDR          eGenes
1  ALOFT ENSG00000073584 7.3307e-29 2.811162e-30 SMARCE1
2  ALOFT ENSG00000197728 1.4197e-27 5.093644e-29 RPS26
3  ALOFT ENSG00000065361 3.9589e-09 1.721136e-10 ERBB3
4  ALOFT ENSG00000148399 4.3954e-07 2.053128e-08 DPH7
5  ALOFT ENSG00000134470 2.1376e-05 1.297504e-06 IL15RA
6  ALOFT ENSG00000134987 1.4580e-04 8.133146e-06 WDR36
7  ALOFT ENSG00000180902 5.4611e-04 3.337787e-05 D2HGDH
8  ALOFT ENSG00000197070 5.4649e-02 4.706086e-03 ARRDC1
9  ALOFT ENSG00000141655 1.1080e-01 1.054306e-02 TNFRSF11A
10 ALOFT ENSG00000065675 1.7726e-01 1.884326e-02 PRKCQ
11 ALOFT ENSG00000174125 4.1298e-01 6.127004e-02 TLR1

In [64]:
saveRDS(prior_tbl, "../output/E2G_analysis/prior_study_genes_evidence.RDS")

In [56]:
prior_tbl$Asthma_eGene <- 
  prior_tbl$CandidateGenes %in% eGenes_combined$eGenes[eGenes_combined$study == "ALOFT"]
gene_tbl$Asthma_eGene <- 
  gene_tbl$LinkedGene %in% eGenes_combined$eGenes[eGenes_combined$study == "ALOFT"]

In [59]:
prior_tbl$CandidateGenes %in% riskGenes_combined

 [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[13] FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
[25] FALSE FALSE  TRUE  TRUE

In [60]:
prior_tbl$risk_genes <- 
  prior_tbl$CandidateGenes %in% riskGenes_combined

In [61]:
gene_tbl$risk_genes <- 
  gene_tbl$LinkedGene %in% riskGenes_combined

In [62]:
prior_tbl

   CandidateGenes LinkedGene          snps                    Lung_eGene
1  IL2RA          IL15RA,IL2RA        rs12722502              FALSE
2  PRKCQ          IL15RA,IL2RA        rs12722502              FALSE
3  PRKCQ          PRKCQ               rs2255088               FALSE
4  IL2RA          PRKCQ               rs2255088               FALSE
5  CXCR5          CXCR5,DDX6          rs12365699,rs4936444    FALSE
6  OVOL1          OVOL1               rs10791824              FALSE
7  LRRC32         LRRC32              rs55646091,rs11236797   FALSE
8  RPS26          ERBB3,IKZF4,RPS26   rs705704,rs705705       FALSE
9  STAT6          LRP1                rs12368672               TRUE
10 SMAD3          IQCH                rs117683492             FALSE
11 MAP2K5         IQCH                rs117683492             FALSE
12 CCR7           CCR7,SMARCE1        rs9893132               FALSE
13 SMARCE1        CCR7,SMARCE1        rs9893132                TRUE
14 CCR7           CCR7,SMARCE1        rs11656173              FALSE
15 SMARCE1        CCR7,SMARCE1        rs11656173               TRUE
16 TBX21          OSBPL7,TBX21        rs56308324              FALSE
17 TNFRSF11A      TNFRSF11A           rs8086340               FALSE
18 SLC7A10        CEBPA               rs118013485,rs117710327 FALSE
19 CEBPA          CEBPA               rs118013485,rs117710327  TRUE
20 TNFSF4         TNFSF4              rs11811856              FALSE
21 CCL20          CCL20               rs1811711                TRUE
22 D2HGDH         D2HGDH              rs5839764               FALSE
23 CCR4           CCR4,TMPPE,TRIM71   rs35570272              FALSE
24 TLR10          TLR1                rs56357984              FALSE
25 TLR1           TLR1                rs56357984              FALSE
26 IRF1           IRF1                rs2548992,rs2057656      TRUE
27 BACH2          BACH2               rs905671,rs943689       FALSE
28 ARRDC1         ARRDC1,DPH7,CACNA1B rs117137535              TRUE
   Asthma_eGene risk_genes
1  FALSE         TRUE
2   TRUE         TRUE
3   TRUE         TRUE
4  FALSE         TRUE
5  FALSE        FALSE
6  FALSE        FALSE
7  FALSE        FALSE
8   TRUE        FALSE
9  FALSE        FALSE
10  TRUE        FALSE
11  TRUE        FALSE
12 FALSE        FALSE
13  TRUE        FALSE
14 FALSE        FALSE
15  TRUE        FALSE
16 FALSE        FALSE
17  TRUE        FALSE
18 FALSE        FALSE
19 FALSE        FALSE
20 FALSE         TRUE
21 FALSE        FALSE
22  TRUE        FALSE
23 FALSE        FALSE
24  TRUE        FALSE
25  TRUE        FALSE
26 FALSE        FALSE
27 FALSE         TRUE
28  TRUE         TRUE

In [63]:
gene_tbl

   LinkedGene trait snps                    Lung_eGene Asthma_eGene risk_genes
1  IL15RA     coa   rs12722502              FALSE       TRUE        FALSE
2  IL2RA      coa   rs12722502              FALSE      FALSE         TRUE
3  PRKCQ      coa   rs2255088               FALSE       TRUE         TRUE
4  CXCR5      coa   rs12365699,rs4936444    FALSE      FALSE        FALSE
5  DDX6       coa   rs12365699,rs4936444    FALSE      FALSE         TRUE
6  OVOL1      coa   rs10791824              FALSE      FALSE        FALSE
7  LRRC32     coa   rs55646091,rs11236797   FALSE      FALSE        FALSE
8  ERBB3      coa   rs705704,rs705705       FALSE       TRUE        FALSE
9  IKZF4      coa   rs705704,rs705705       FALSE      FALSE        FALSE
10 RPS26      coa   rs705704,rs705705       FALSE       TRUE        FALSE
11 LRP1       coa   rs12368672              FALSE      FALSE        FALSE
12 IQCH       coa   rs117683492             FALSE      FALSE        FALSE
13 CCR7       coa   rs9893132               FALSE      FALSE        FALSE
14 SMARCE1    coa   rs9893132                TRUE       TRUE        FALSE
15 CCR7       coa   rs11656173              FALSE      FALSE        FALSE
16 SMARCE1    coa   rs11656173               TRUE       TRUE        FALSE
17 OSBPL7     coa   rs56308324              FALSE      FALSE        FALSE
18 TBX21      coa   rs56308324              FALSE      FALSE        FALSE
19 TNFRSF11A  coa   rs8086340               FALSE       TRUE        FALSE
20 CEBPA      coa   rs118013485,rs117710327  TRUE      FALSE        FALSE
21 TNFSF4     coa   rs11811856              FALSE      FALSE         TRUE
22 CCL20      coa   rs1811711                TRUE      FALSE        FALSE
23 D2HGDH     aoa   rs5839764               FALSE       TRUE        FALSE
24 CCR4       coa   rs35570272              FALSE      FALSE        FALSE
25 TMPPE      coa   rs35570272              FALSE      FALSE        FALSE
26 TRIM71     coa   rs35570272              FALSE      FALSE        FALSE
27 TLR1       coa   rs56357984              FALSE       TRUE        FALSE
28 IRF1       coa   rs2548992,rs2057656      TRUE      FALSE        FALSE
29 BACH2      aoa   rs905671,rs943689       FALSE      FALSE         TRUE
30 ARRDC1     coa   rs117137535              TRUE       TRUE         TRUE
31 DPH7       coa   rs117137535             FALSE       TRUE        FALSE
32 CACNA1B    coa   rs117137535             FALSE      FALSE        FALSE
33 CCR4       coa   rs6795737               FALSE      FALSE        FALSE
34 TMPPE      coa   rs6795737               FALSE      FALSE        FALSE
35 TRIM71     coa   rs6795737               FALSE      FALSE        FALSE
36 WDR36      coa   rs2289277               FALSE       TRUE        FALSE
37 IL13       aoa   rs115008099             FALSE      FALSE        FALSE